# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rbp28668/SkyEcho/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rbp28668/SkyEcho/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rbp28668/SkyEcho/cpp/CMakeFiles /home/rbp28668/SkyEcho/cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rbp28668/SkyEcho/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SkyEcho2

# Build rule for target.
SkyEcho2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SkyEcho2
.PHONY : SkyEcho2

# fast build rule for target.
SkyEcho2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/build
.PHONY : SkyEcho2/fast

NMEAData.o: NMEAData.cpp.o
.PHONY : NMEAData.o

# target to build an object file
NMEAData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/NMEAData.cpp.o
.PHONY : NMEAData.cpp.o

NMEAData.i: NMEAData.cpp.i
.PHONY : NMEAData.i

# target to preprocess a source file
NMEAData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/NMEAData.cpp.i
.PHONY : NMEAData.cpp.i

NMEAData.s: NMEAData.cpp.s
.PHONY : NMEAData.s

# target to generate assembly for a file
NMEAData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/NMEAData.cpp.s
.PHONY : NMEAData.cpp.s

fcs.o: fcs.cpp.o
.PHONY : fcs.o

# target to build an object file
fcs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/fcs.cpp.o
.PHONY : fcs.cpp.o

fcs.i: fcs.cpp.i
.PHONY : fcs.i

# target to preprocess a source file
fcs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/fcs.cpp.i
.PHONY : fcs.cpp.i

fcs.s: fcs.cpp.s
.PHONY : fcs.s

# target to generate assembly for a file
fcs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/fcs.cpp.s
.PHONY : fcs.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/main.cpp.s
.PHONY : main.cpp.s

message_handler.o: message_handler.cpp.o
.PHONY : message_handler.o

# target to build an object file
message_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/message_handler.cpp.o
.PHONY : message_handler.cpp.o

message_handler.i: message_handler.cpp.i
.PHONY : message_handler.i

# target to preprocess a source file
message_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/message_handler.cpp.i
.PHONY : message_handler.cpp.i

message_handler.s: message_handler.cpp.s
.PHONY : message_handler.s

# target to generate assembly for a file
message_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/message_handler.cpp.s
.PHONY : message_handler.cpp.s

socket.o: socket.cpp.o
.PHONY : socket.o

# target to build an object file
socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/socket.cpp.o
.PHONY : socket.cpp.o

socket.i: socket.cpp.i
.PHONY : socket.i

# target to preprocess a source file
socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/socket.cpp.i
.PHONY : socket.cpp.i

socket.s: socket.cpp.s
.PHONY : socket.s

# target to generate assembly for a file
socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/socket.cpp.s
.PHONY : socket.cpp.s

state.o: state.cpp.o
.PHONY : state.o

# target to build an object file
state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/state.cpp.o
.PHONY : state.cpp.o

state.i: state.cpp.i
.PHONY : state.i

# target to preprocess a source file
state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/state.cpp.i
.PHONY : state.cpp.i

state.s: state.cpp.s
.PHONY : state.s

# target to generate assembly for a file
state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/state.cpp.s
.PHONY : state.cpp.s

transport.o: transport.cpp.o
.PHONY : transport.o

# target to build an object file
transport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/transport.cpp.o
.PHONY : transport.cpp.o

transport.i: transport.cpp.i
.PHONY : transport.i

# target to preprocess a source file
transport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/transport.cpp.i
.PHONY : transport.cpp.i

transport.s: transport.cpp.s
.PHONY : transport.s

# target to generate assembly for a file
transport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SkyEcho2.dir/build.make CMakeFiles/SkyEcho2.dir/transport.cpp.s
.PHONY : transport.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SkyEcho2"
	@echo "... NMEAData.o"
	@echo "... NMEAData.i"
	@echo "... NMEAData.s"
	@echo "... fcs.o"
	@echo "... fcs.i"
	@echo "... fcs.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... message_handler.o"
	@echo "... message_handler.i"
	@echo "... message_handler.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... state.o"
	@echo "... state.i"
	@echo "... state.s"
	@echo "... transport.o"
	@echo "... transport.i"
	@echo "... transport.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

